apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: "{{ .Values.name }}-dep"
  name: "{{ .Values.name }}-dep"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: "{{ .Values.name }}-dep"
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: "{{ .Values.name }}-dep"
    spec:
      containers:
      - image: nginx:{{ .Values.image.tag }}
        name: nginx
        resources: 
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
status: {}
