apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: "{{ .Values.name }}-svc"
  name: "{{ .Values.name }}-svc"
spec:
  ports:
  - port: {{  .Values.port }}
    protocol: TCP
    targetPort: {{  .Values.targetPort }}
  selector:
    app: "{{ .Values.name }}-dep"
status:
  loadBalancer: {}
