- name: Install httpd
  hosts: all
  become: true
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: present

  - name: Check State httpd
    systemd:
      name: httpd
      state: started
    register: status_httpd

  - name: Check State httpd
    debug:
      var: status_httpd
      verbosity: 2
  
  - name: Create file index.html
    copy:
      content: 'Welcome to my web server'
      dest: /var/www/html/index.html

  - name: Open Http port
    firewalld:
      service: http
      permanent: yes
      state: enabled

  - name: restart firewalld
    systemd:
      name: firewalld
      state: restarted
      enabled: yes
