apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grabber
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grabber
rules:
- apiGroups: [""] 
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grabber
subjects:
- kind: ServiceAccount
  name: grabber
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: grabber
  apiGroup: rbac.authorization.k8s.io
---

