apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  labels:
    app: elasticsearch
spec:
  storageClassName: default
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 25Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce 
  hostPath:
    path: "/mnt/data"