install_delete: install ## (install/delete) 
anonymous_enable: yes
local_enable: NO
write_enable: YES
local_umask: 022
anon_upload_enable: YES
anon_mkdir_write_enable: YES
dirmessage_enable: YES
xferlog_enable: YES
connect_from_port_20: YES
xferlog_std_format: YES
listen: yes
listen_ipv6: no
pam_service_name: vsftpd
userlist_enable: YES
anon_other_write_enable: YES
anon_umask: 022
pasv_enable: YES
pasv_min_port: 50000
pasv_max_port: 51000